package com.dna.jopt.touroptimizer.java.examples.basic.io_03;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
/*-
 * #%L
 * JOpt TourOptimizer Examples
 * %%
 * Copyright (C) 2017 - 2020 DNA Evolutions GmbH
 * %%
 * This file is subject to the terms and conditions defined in file 'src/main/resources/LICENSE.txt',
 * which is part of this repository.
 *
 * If not, see <https://www.dna-evolutions.com/>.
 * #L%
 */
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import java.util.concurrent.ExecutionException;

import org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream;
import org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream;

import com.dna.jopt.config.convert.ConvertException;
import com.dna.jopt.config.serialize.SerializationException;
import com.dna.jopt.framework.body.IOptimization;
import com.dna.jopt.framework.body.Optimization;
import com.dna.jopt.framework.exception.caught.InvalidLicenceException;
import com.dna.jopt.framework.outcomewrapper.IOptimizationProgress;
import com.dna.jopt.framework.outcomewrapper.IOptimizationResult;
import com.dna.jopt.io.importing.IOptimizationImporter;
import com.dna.jopt.io.importing.json.OptimizationJSONImporter;
import com.dna.jopt.touroptimizer.java.examples.ExampleLicenseHelper;

/**
 * This example shows how to load an optimization state from a JSON file.
 *
 * @author DNA
 * @version Mar 26, 2021
 * @since Mar 26, 2021
 */
public class LoadOptimizationFromJsonString extends Optimization {

  
  public static final String JSON_SNAPSHOT = "{\r\n"
  	+ "	\"optimizationStatus\": {\r\n"
  	+ "		\"statusDescription\": \"SUCCESS_WITH_SOLUTION\",\r\n"
  	+ "		\"error\": \"NO_ERROR\",\r\n"
  	+ "		\"status\": \"SUCCESS_WITH_SOLUTION\"\r\n"
  	+ "	},\r\n"
  	+ "	\"createdTimeStamp\": 1741101853520,\r\n"
  	+ "	\"creator\": \"DEFAULT_CREATOR\",\r\n"
  	+ "	\"ident\": \"JOpt-Run-1741101851742\",\r\n"
  	+ "	\"nodes\": [\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Aachen\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"Aachen\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Oberhausen\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 51.4667,\r\n"
  	+ "					\"longitude\": 6.85,\r\n"
  	+ "					\"locationId\": \"Oberhausen\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Essen\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 51.45,\r\n"
  	+ "					\"longitude\": 7.01667,\r\n"
  	+ "					\"locationId\": \"Essen\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Wuppertal\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 51.2667,\r\n"
  	+ "					\"longitude\": 7.18333,\r\n"
  	+ "					\"locationId\": \"Wuppertal\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Koeln1\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 50.9333,\r\n"
  	+ "					\"longitude\": 6.95,\r\n"
  	+ "					\"locationId\": \"Koeln1\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Koeln\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 50.9333,\r\n"
  	+ "					\"longitude\": 6.95,\r\n"
  	+ "					\"locationId\": \"Koeln\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Heilbronn\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 49.1403,\r\n"
  	+ "					\"longitude\": 9.22,\r\n"
  	+ "					\"locationId\": \"Heilbronn\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Stuttgart\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"position\": {\r\n"
  	+ "					\"latitude\": 48.7667,\r\n"
  	+ "					\"longitude\": 9.18333,\r\n"
  	+ "					\"locationId\": \"Stuttgart\"\r\n"
  	+ "				},\r\n"
  	+ "				\"typeName\": \"Geo\"\r\n"
  	+ "			},\r\n"
  	+ "			\"openingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\"\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"visitDuration\": \"PT20M\",\r\n"
  	+ "			\"priority\": 1\r\n"
  	+ "		}\r\n"
  	+ "	],\r\n"
  	+ "	\"resources\": [\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"Jack\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"typeName\": \"Capacity\"\r\n"
  	+ "			},\r\n"
  	+ "			\"position\": {\r\n"
  	+ "				\"latitude\": 50.775346,\r\n"
  	+ "				\"longitude\": 6.083887,\r\n"
  	+ "				\"locationId\": \"Jack\"\r\n"
  	+ "			},\r\n"
  	+ "			\"workingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\",\r\n"
  	+ "					\"isAvailableForStay\": false\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T19:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\",\r\n"
  	+ "					\"isAvailableForStay\": false\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"maxTime\": \"PT8H\",\r\n"
  	+ "			\"maxDistance\": \"1200.0 km\",\r\n"
  	+ "			\"co2emissionFactor\": 0.377\r\n"
  	+ "		},\r\n"
  	+ "		{\r\n"
  	+ "			\"id\": \"John\",\r\n"
  	+ "			\"type\": {\r\n"
  	+ "				\"typeName\": \"Capacity\"\r\n"
  	+ "			},\r\n"
  	+ "			\"position\": {\r\n"
  	+ "				\"latitude\": 50.775346,\r\n"
  	+ "				\"longitude\": 6.083887,\r\n"
  	+ "				\"locationId\": \"John\"\r\n"
  	+ "			},\r\n"
  	+ "			\"workingHours\": [\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-06T16:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\",\r\n"
  	+ "					\"isAvailableForStay\": false\r\n"
  	+ "				},\r\n"
  	+ "				{\r\n"
  	+ "					\"begin\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "					\"end\": \"2020-03-07T19:00:00Z\",\r\n"
  	+ "					\"zoneId\": \"Europe/Berlin\",\r\n"
  	+ "					\"isAvailableForStay\": false\r\n"
  	+ "				}\r\n"
  	+ "			],\r\n"
  	+ "			\"maxTime\": \"PT14H\",\r\n"
  	+ "			\"maxDistance\": \"1200.0 km\",\r\n"
  	+ "			\"co2emissionFactor\": 0.377\r\n"
  	+ "		}\r\n"
  	+ "	],\r\n"
  	+ "	\"elementConnections\": [],\r\n"
  	+ "	\"optimizationOptions\": {\r\n"
  	+ "		\"properties\": {\r\n"
  	+ "			\"JOpt.Algorithm.GE.OnProgressOutPercentage\": \"1.0\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.2Opt.Threshold\": \"10\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.GE.doForceReselect\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.GE.numReselects\": \"3\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.RequireHoursOverlap\": \"TRUE\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.SA.doForceReselect\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Algorithm.Operator.SA.numReselects\": \"5\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.CoolingRate\": \"0.999985\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.NumIterations\": \"100000\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.NumRepetions\": \"1\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.OnProgressOutPercentage\": \"1.0\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.StartingTemperature\": \"10.0\",\r\n"
  	+ "			\"JOpt.Algorithm.PreOptimization.SA.StartingTemperatureLoadedSnapshot\": \"0.1\",\r\n"
  	+ "			\"JOpt.Algorithm.Relation.NestingLimit\": \"100\",\r\n"
  	+ "			\"JOpt.Algorithm.tryUseCluster2Opt\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Algorithm.tryUseClusterInsertion\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Assisted\": \"TRUE\",\r\n"
  	+ "			\"JOpt.AutoFilter\": \"FALSE\",\r\n"
  	+ "			\"JOpt.AutoFilter.EarlyArrivalMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoFilter.LateArrivalMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoFilter.RouteDistanceExceedMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoFilter.WorkingHoursExceedMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoFilter.afterFilteringResult\": \"FALSE\",\r\n"
  	+ "			\"JOpt.AutoFilter.beforeFilteringResult\": \"FALSE\",\r\n"
  	+ "			\"JOpt.AutoFilter.canDisableNodeProtection\": \"TRUE\",\r\n"
  	+ "			\"JOpt.AutoFilter.collectivePenalization.maxImportance\": \"5\",\r\n"
  	+ "			\"JOpt.AutoFilter.tryAvoidSplittingJoinedClusters\": \"FALSE\",\r\n"
  	+ "			\"JOpt.AutoFilter.tryGracefulNodeFiltering\": \"TRUE\",\r\n"
  	+ "			\"JOpt.AutoFilter.usePostOptimizationAfterStrictFiltering\": \"TRUE\",\r\n"
  	+ "			\"JOpt.AutoFilter.useStrictFilterOnLastExecution\": \"TRUE\",\r\n"
  	+ "			\"JOpt.AutoForceFilter.EarlyArrivalMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoForceFilter.LateArrivalMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoForceFilter.RouteDistanceExceedMargin\": \"0\",\r\n"
  	+ "			\"JOpt.AutoForceFilter.WorkingHoursExceedMargin\": \"0\",\r\n"
  	+ "			\"JOpt.CO.ActiveTimeTrigger\": \"FALSE\",\r\n"
  	+ "			\"JOpt.CO.AutoSyncJoptTime\": \"FALSE\",\r\n"
  	+ "			\"JOpt.CapacityDegradation.TreatSameLocationsAsOne\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Clustering.AutoZoneCodeClusters\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Clustering.AutoZoneCodeClusters.isHard\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Clustering.JointVisitDuration.doUseDistanceDivider\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Clustering.MaxDistanceUtilization\": \"200.0\",\r\n"
  	+ "			\"JOpt.Clustering.MaxDurationUtilization\": \"80.0\",\r\n"
  	+ "			\"JOpt.Clustering.PenlalizeZoneCodeCrossing\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Clustering.PenlalizeZoneCodeCrossingMultiplier\": \"1.0\",\r\n"
  	+ "			\"JOpt.Clustering.ReassignOrphanedNodes\": \"TRUE\",\r\n"
  	+ "			\"JOpt.Clustering.ResourceDutyHoursSplitValue\": \"10\",\r\n"
  	+ "			\"JOpt.Clustering.ResourceSplitValue\": \"30\",\r\n"
  	+ "			\"JOpt.Clustering.ShowDebugOutput\": \"FALSE\",\r\n"
  	+ "			\"JOpt.CostAssessment.suppressInactiveFinalizedRouteCosts\": \"TRUE\",\r\n"
  	+ "			\"JOpt.CostAssessment.useAverageCost\": \"FALSE\",\r\n"
  	+ "			\"JOpt.DebugMode.NodeChecking\": \"TRUE\",\r\n"
  	+ "			\"JOpt.EntityValidation.Debug\": \"FALSE\",\r\n"
  	+ "			\"JOpt.FuzzyDemand\": \"0\",\r\n"
  	+ "			\"JOpt.IntermediateStage.ThrowResults\": \"FALSE\",\r\n"
  	+ "			\"JOpt.JOptPopulationSize\": \"100\",\r\n"
  	+ "			\"JOpt.JointVisitDuration.maxRadiusMeter\": \"10.0\",\r\n"
  	+ "			\"JOpt.JointVisitDuration.routeTimeBonusFactor\": \"0.0\",\r\n"
  	+ "			\"JOpt.KeepZeroDriveForEventNodes\": \"FALSE\",\r\n"
  	+ "			\"JOpt.Lockdown.Blockpillar.endOffset\": \"0\",\r\n"
  	+ "			\"JOpt.Lockdown.Blockpillar.startOffset\": \"0\",\r\n"
  	+ "			\"JOpt.Lockdown.LockdownUnchangedRoutes\": \"TRUE\",\r\n"
  	+ "			\"JOpt.MovingEventNodes\": \"TRUE\",\r\n"
  	+ "			\"JOpt.Multicore\": \"1\",\r\n"
  	+ "			\"JOpt.NumCPUCores\": \"4\",\r\n"
  	+ "			\"JOpt.PerformanceMode\": \"FALSE\",\r\n"
  	+ "			\"JOpt.PillarDropper.AllowRescheduleMaximalRouteDistanceExceeded\": \"TRUE\",\r\n"
  	+ "			\"JOpt.PillarDropper.AllowRescheduleWorkingHoursExceeded\": \"TRUE\",\r\n"
  	+ "			\"JOpt.PlausibilityGuard.PropertyChecker.Active\": \"TRUE\",\r\n"
  	+ "			\"JOpt.PropertyChecker.ShowWarnings\": \"TRUE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.AfterEndAnchor\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.CapacityOverload\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.DoubleBooking\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.MaximalRouteDistanceExceeded\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.NodeType\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.RelationShip\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.ResourceMismatch\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.TimeWindow.Early\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.TimeWindow.Late\": \"FALSE\",\r\n"
  	+ "			\"JOpt.SelectiveAutoFilter.WorkingHoursExceeded\": \"FALSE\",\r\n"
  	+ "			\"JOpt.UnlocatedIdleTime\": \"FALSE\",\r\n"
  	+ "			\"JOpt.plausibility.doInputCheck\": \"TRUE\",\r\n"
  	+ "			\"JOpt.plausibility.doInputCheck.doCapacityCheck\": \"TRUE\",\r\n"
  	+ "			\"JOptExitCondition.JOptGenerationCount\": \"2000\",\r\n"
  	+ "			\"JOptWeight.CO2Emission\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.Capacity\": \"50.0\",\r\n"
  	+ "			\"JOptWeight.ColorCapacity\": \"10.0\",\r\n"
  	+ "			\"JOptWeight.CompactingFactor\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.DistanceExceeded\": \"10.0\",\r\n"
  	+ "			\"JOptWeight.DistanceVariationPattern\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.ExpertiseLevelPreference\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.NodeCompactingFactor\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.NodeImportance\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.NodeType\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.PreferableResource\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.Relationships\": \"100.0\",\r\n"
  	+ "			\"JOptWeight.ResourceActive\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.ResourceLocationBias\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.ResourceRadiusDrivingDistance\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.ResourceRadiusDrivingTime\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.ResourceWorkingTimeBalance\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.RouteDistance\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.RouteTime\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.TimeExceeded\": \"100.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.AfterEndPillarAnchor\": \"1000.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.FlexTimePenalizeFactor\": \"0.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.OfferedNodeCostMulitplier\": \"2.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.ServiceHours\": \"10.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.TimeWindowEarlyFactor\": \"10.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.TimeWindowEarlyFactorAtFirstNode\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.TimeWindow.TimeWindowLateFactor\": \"100.0\",\r\n"
  	+ "			\"JOptWeight.TotalDistance\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.TotalTime\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.UnPreferableResource\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.UselessUnloadAllVisitation\": \"1.0\",\r\n"
  	+ "			\"JOptWeight.WorkingTime\": \"5.0\",\r\n"
  	+ "			\"JOptWeight.ZoneCode\": \"10.0\"\r\n"
  	+ "		}\r\n"
  	+ "	},\r\n"
  	+ "	\"coreBuildOptions\": {\r\n"
  	+ "		\"buildCoreProperties\": {\r\n"
  	+ "			\"jopt.core.maven-surefire-plugin.version\": \"3.2.2\",\r\n"
  	+ "			\"jopt.core.git.commit.author.time\": \"20250208-112732\",\r\n"
  	+ "			\"jopt.core.jopt.version.number\": \"7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.jackson-databind.version\": \"2.18.2\",\r\n"
  	+ "			\"jopt.core.git.dirty\": \"false\",\r\n"
  	+ "			\"jopt.core.testng.version\": \"7.10.2\",\r\n"
  	+ "			\"jopt.core.proguard.core.version\": \"9.1.7\",\r\n"
  	+ "			\"jopt.core.git.build.host\": \"f0771345-190d-4768-b380-52d82fda3acd-9dtcv\",\r\n"
  	+ "			\"jopt.core.git.build.time\": \"20250208-113058\",\r\n"
  	+ "			\"jopt.core.jackson-datatype-guava.version\": \"2.18.2\",\r\n"
  	+ "			\"jopt.core.git.commit.user.name\": \"Jens Richter\",\r\n"
  	+ "			\"jopt.core.jackson-datatype-jdk8.version\": \"2.18.2\",\r\n"
  	+ "			\"jopt.core.git.local.branch.ahead\": \"NO_REMOTE\",\r\n"
  	+ "			\"jopt.core.maven-shade-plugin.version\": \"3.5.1\",\r\n"
  	+ "			\"jopt.core.bson.version\": \"5.2.1\",\r\n"
  	+ "			\"jopt.core.git.closest.tag.commit.count\": \"0\",\r\n"
  	+ "			\"jopt.core.wagon-maven-plugin.version\": \"2.0.2\",\r\n"
  	+ "			\"jopt.core.maven-deploy-plugin.version\": \"3.1.1\",\r\n"
  	+ "			\"jopt.core.commons-math3.version\": \"3.6.1\",\r\n"
  	+ "			\"jopt.core.jacoco-maven-plugin.version\": \"0.8.8\",\r\n"
  	+ "			\"jopt.core.maven.compiler.target\": \"17\",\r\n"
  	+ "			\"jopt.core.unit-api.version\": \"2.1\",\r\n"
  	+ "			\"jopt.core.jopt.version.postfix\": \"\",\r\n"
  	+ "			\"jopt.core.project.build.sourceEncoding\": \"cp1252\",\r\n"
  	+ "			\"jopt.core.wagon-ssh.version\": \"3.5.3\",\r\n"
  	+ "			\"jopt.core.git.branch\": \"c647e3e397a5cbd7e98a6ce3a8211a1aec831b58\",\r\n"
  	+ "			\"jopt.core.git-commit-id-plugin.version\": \"4.9.10\",\r\n"
  	+ "			\"jopt.core.maven-javadoc-plugin.version\": \"3.6.3\",\r\n"
  	+ "			\"jopt.core.log4j-core.version\": \"2.24.3\",\r\n"
  	+ "			\"jopt.core.maven-source-plugin.version\": \"3.3.0\",\r\n"
  	+ "			\"jopt.core.spring-data-mongodb.version\": \"4.4.2\",\r\n"
  	+ "			\"jopt.core.datafactory.version\": \"0.8\",\r\n"
  	+ "			\"jopt.core.commons-compress.version\": \"1.27.1\",\r\n"
  	+ "			\"jopt.core.java.version.target\": \"17\",\r\n"
  	+ "			\"jopt.core.jackson-datatype-jsr310.version\": \"2.18.2\",\r\n"
  	+ "			\"jopt.core.build.time.utc\": \"2025-02-08T11:30:54Z\",\r\n"
  	+ "			\"jopt.core.git.commit.id.describe\": \"v7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.java.version.source\": \"17\",\r\n"
  	+ "			\"jopt.core.properties-maven-plugin.version\": \"1.1.0\",\r\n"
  	+ "			\"jopt.core.unit-ri.version\": \"1.0.3\",\r\n"
  	+ "			\"jopt.core.value.version\": \"2.10.1\",\r\n"
  	+ "			\"jopt.core.git.tags\": \"v7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.git.commit.id\": \"c647e3e397a5cbd7e98a6ce3a8211a1aec831b58\",\r\n"
  	+ "			\"jopt.core.poi.version\": \"5.4.0\",\r\n"
  	+ "			\"jopt.core.git.commit.id.describe-short\": \"v7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.commons-lang3.version\": \"3.17.0\",\r\n"
  	+ "			\"jopt.core.maven.test.skip\": \"true\",\r\n"
  	+ "			\"jopt.core.jackson-module-parameter-names.version\": \"2.18.2\",\r\n"
  	+ "			\"jopt.core.maven.compiler.source\": \"17\",\r\n"
  	+ "			\"jopt.core.git.local.branch.behind\": \"NO_REMOTE\",\r\n"
  	+ "			\"jopt.core.git.build.number\": \"2546\",\r\n"
  	+ "			\"jopt.core.git.commit.committer.time\": \"20250208-112732\",\r\n"
  	+ "			\"jopt.core.git.build.version\": \"7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.git.commit.id.abbrev\": \"c647e3e\",\r\n"
  	+ "			\"jopt.core.guava.version\": \"33.4.0-jre\",\r\n"
  	+ "			\"jopt.core.swagger-annotations.version\": \"2.2.28\",\r\n"
  	+ "			\"jopt.core.license-maven-plugin.version\": \"2.0.0\",\r\n"
  	+ "			\"jopt.core.jts-core.version\": \"1.20.0\",\r\n"
  	+ "			\"jopt.core.javafaker.version\": \"1.0.2\",\r\n"
  	+ "			\"jopt.core.git.total.commit.count\": \"3304\",\r\n"
  	+ "			\"jopt.core.git.closest.tag.name\": \"v7.5.2-j17\",\r\n"
  	+ "			\"jopt.core.poi-ooxml.version\": \"5.4.0\",\r\n"
  	+ "			\"jopt.core.git.commit.time\": \"20250208-112732\",\r\n"
  	+ "			\"jopt.core.hamcrest.version\": \"3.0\",\r\n"
  	+ "			\"jopt.core.maven-compiler-plugin.version\": \"3.12.1\",\r\n"
  	+ "			\"jopt.core.proguard-maven-plugin.version\": \"2.6.0\",\r\n"
  	+ "			\"jopt.core.proguard.base.version\": \"7.6.1\",\r\n"
  	+ "			\"jopt.core.rxjava.version\": \"3.1.10\",\r\n"
  	+ "			\"jopt.core.wagon-ftp.version\": \"3.5.3\"\r\n"
  	+ "		}\r\n"
  	+ "	},\r\n"
  	+ "	\"solution\": {\r\n"
  	+ "		\"createdTimeStamp\": 1741101853520,\r\n"
  	+ "		\"creator\": \"DEFAULT_CREATOR\",\r\n"
  	+ "		\"ident\": \"JOpt-Run-1741101851742\",\r\n"
  	+ "		\"header\": {\r\n"
  	+ "			\"numRoutes\": 4,\r\n"
  	+ "			\"numScheduledRoutes\": 2,\r\n"
  	+ "			\"totElements\": 10,\r\n"
  	+ "			\"unassignedElementIds\": [],\r\n"
  	+ "			\"totCost\": 847.033054487167,\r\n"
  	+ "			\"totTime\": \"PT12H34M5.115S\",\r\n"
  	+ "			\"totIdleTime\": \"PT0S\",\r\n"
  	+ "			\"totProdTime\": \"PT2H40M\",\r\n"
  	+ "			\"totTranTime\": \"PT9H54M5.115S\",\r\n"
  	+ "			\"totTermiTime\": \"PT4H1M10.835S\",\r\n"
  	+ "			\"totDistance\": \"784192.6169871669 m\",\r\n"
  	+ "			\"totTermiDistance\": \"318358.3783121061 m\",\r\n"
  	+ "			\"jobViolations\": []\r\n"
  	+ "		},\r\n"
  	+ "		\"routes\": [\r\n"
  	+ "			{\r\n"
  	+ "				\"header\": {\r\n"
  	+ "					\"cost\": 1.6666666666666668,\r\n"
  	+ "					\"time\": \"PT20M\",\r\n"
  	+ "					\"idleTime\": \"PT0S\",\r\n"
  	+ "					\"prodTime\": \"PT20M\",\r\n"
  	+ "					\"tranTime\": \"PT0S\",\r\n"
  	+ "					\"termiTime\": \"PT0S\",\r\n"
  	+ "					\"distance\": \"0.0 m\",\r\n"
  	+ "					\"termiDistance\": \"0.0 m\",\r\n"
  	+ "					\"routeViolations\": [],\r\n"
  	+ "					\"isClosed\": true,\r\n"
  	+ "					\"isAlternateDestination\": false\r\n"
  	+ "				},\r\n"
  	+ "				\"id\": 0,\r\n"
  	+ "				\"resourceId\": \"Jack\",\r\n"
  	+ "				\"startTime\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "				\"startElementId\": \"Jack\",\r\n"
  	+ "				\"startPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"Jack\"\r\n"
  	+ "				},\r\n"
  	+ "				\"endElementId\": \"Jack\",\r\n"
  	+ "				\"endPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"Jack\"\r\n"
  	+ "				},\r\n"
  	+ "				\"optimizableElementIds\": [\r\n"
  	+ "					\"Aachen\"\r\n"
  	+ "				],\r\n"
  	+ "				\"nonOptimizableElementIds\": [],\r\n"
  	+ "				\"optionalOptimizableElementIds\": [],\r\n"
  	+ "				\"pillarElementIds\": [],\r\n"
  	+ "				\"elementDetails\": [],\r\n"
  	+ "				\"pillarLatestEffectiveArrivalOffsetMap\": {},\r\n"
  	+ "				\"flags\": [],\r\n"
  	+ "				\"isFinalized\": false,\r\n"
  	+ "				\"isInactive\": false,\r\n"
  	+ "				\"isLockedDown\": false\r\n"
  	+ "			},\r\n"
  	+ "			{\r\n"
  	+ "				\"header\": {\r\n"
  	+ "					\"cost\": 0.0,\r\n"
  	+ "					\"time\": \"PT0S\",\r\n"
  	+ "					\"idleTime\": \"PT0S\",\r\n"
  	+ "					\"prodTime\": \"PT0S\",\r\n"
  	+ "					\"tranTime\": \"PT0S\",\r\n"
  	+ "					\"termiTime\": \"PT0S\",\r\n"
  	+ "					\"distance\": \"0.0 m\",\r\n"
  	+ "					\"termiDistance\": \"0.0 m\",\r\n"
  	+ "					\"routeViolations\": [],\r\n"
  	+ "					\"isClosed\": true,\r\n"
  	+ "					\"isAlternateDestination\": false\r\n"
  	+ "				},\r\n"
  	+ "				\"id\": 1,\r\n"
  	+ "				\"resourceId\": \"Jack\",\r\n"
  	+ "				\"startTime\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "				\"startElementId\": \"Jack\",\r\n"
  	+ "				\"startPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"Jack\"\r\n"
  	+ "				},\r\n"
  	+ "				\"endElementId\": \"Jack\",\r\n"
  	+ "				\"endPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"Jack\"\r\n"
  	+ "				},\r\n"
  	+ "				\"optimizableElementIds\": [],\r\n"
  	+ "				\"nonOptimizableElementIds\": [],\r\n"
  	+ "				\"optionalOptimizableElementIds\": [],\r\n"
  	+ "				\"pillarElementIds\": [],\r\n"
  	+ "				\"elementDetails\": [],\r\n"
  	+ "				\"pillarLatestEffectiveArrivalOffsetMap\": {},\r\n"
  	+ "				\"flags\": [],\r\n"
  	+ "				\"isFinalized\": false,\r\n"
  	+ "				\"isInactive\": false,\r\n"
  	+ "				\"isLockedDown\": false\r\n"
  	+ "			},\r\n"
  	+ "			{\r\n"
  	+ "				\"header\": {\r\n"
  	+ "					\"cost\": 845.3663878205003,\r\n"
  	+ "					\"time\": \"PT12H14M5.115S\",\r\n"
  	+ "					\"idleTime\": \"PT0S\",\r\n"
  	+ "					\"prodTime\": \"PT2H20M\",\r\n"
  	+ "					\"tranTime\": \"PT9H54M5.115S\",\r\n"
  	+ "					\"termiTime\": \"PT4H1M10.835S\",\r\n"
  	+ "					\"distance\": \"784192.6169871669 m\",\r\n"
  	+ "					\"termiDistance\": \"318358.3783121061 m\",\r\n"
  	+ "					\"routeViolations\": [],\r\n"
  	+ "					\"isClosed\": true,\r\n"
  	+ "					\"isAlternateDestination\": false\r\n"
  	+ "				},\r\n"
  	+ "				\"id\": 2,\r\n"
  	+ "				\"resourceId\": \"John\",\r\n"
  	+ "				\"startTime\": \"2020-03-06T07:00:00Z\",\r\n"
  	+ "				\"startElementId\": \"John\",\r\n"
  	+ "				\"startPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"John\"\r\n"
  	+ "				},\r\n"
  	+ "				\"endElementId\": \"John\",\r\n"
  	+ "				\"endPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"John\"\r\n"
  	+ "				},\r\n"
  	+ "				\"optimizableElementIds\": [\r\n"
  	+ "					\"Oberhausen\",\r\n"
  	+ "					\"Essen\",\r\n"
  	+ "					\"Wuppertal\",\r\n"
  	+ "					\"Koeln1\",\r\n"
  	+ "					\"Koeln\",\r\n"
  	+ "					\"Heilbronn\",\r\n"
  	+ "					\"Stuttgart\"\r\n"
  	+ "				],\r\n"
  	+ "				\"nonOptimizableElementIds\": [],\r\n"
  	+ "				\"optionalOptimizableElementIds\": [],\r\n"
  	+ "				\"pillarElementIds\": [],\r\n"
  	+ "				\"elementDetails\": [],\r\n"
  	+ "				\"pillarLatestEffectiveArrivalOffsetMap\": {},\r\n"
  	+ "				\"flags\": [],\r\n"
  	+ "				\"isFinalized\": false,\r\n"
  	+ "				\"isInactive\": false,\r\n"
  	+ "				\"isLockedDown\": false\r\n"
  	+ "			},\r\n"
  	+ "			{\r\n"
  	+ "				\"header\": {\r\n"
  	+ "					\"cost\": 0.0,\r\n"
  	+ "					\"time\": \"PT0S\",\r\n"
  	+ "					\"idleTime\": \"PT0S\",\r\n"
  	+ "					\"prodTime\": \"PT0S\",\r\n"
  	+ "					\"tranTime\": \"PT0S\",\r\n"
  	+ "					\"termiTime\": \"PT0S\",\r\n"
  	+ "					\"distance\": \"0.0 m\",\r\n"
  	+ "					\"termiDistance\": \"0.0 m\",\r\n"
  	+ "					\"routeViolations\": [],\r\n"
  	+ "					\"isClosed\": true,\r\n"
  	+ "					\"isAlternateDestination\": false\r\n"
  	+ "				},\r\n"
  	+ "				\"id\": 3,\r\n"
  	+ "				\"resourceId\": \"John\",\r\n"
  	+ "				\"startTime\": \"2020-03-07T07:00:00Z\",\r\n"
  	+ "				\"startElementId\": \"John\",\r\n"
  	+ "				\"startPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"John\"\r\n"
  	+ "				},\r\n"
  	+ "				\"endElementId\": \"John\",\r\n"
  	+ "				\"endPosition\": {\r\n"
  	+ "					\"latitude\": 50.775346,\r\n"
  	+ "					\"longitude\": 6.083887,\r\n"
  	+ "					\"locationId\": \"John\"\r\n"
  	+ "				},\r\n"
  	+ "				\"optimizableElementIds\": [],\r\n"
  	+ "				\"nonOptimizableElementIds\": [],\r\n"
  	+ "				\"optionalOptimizableElementIds\": [],\r\n"
  	+ "				\"pillarElementIds\": [],\r\n"
  	+ "				\"elementDetails\": [],\r\n"
  	+ "				\"pillarLatestEffectiveArrivalOffsetMap\": {},\r\n"
  	+ "				\"flags\": [],\r\n"
  	+ "				\"isFinalized\": false,\r\n"
  	+ "				\"isInactive\": false,\r\n"
  	+ "				\"isLockedDown\": false\r\n"
  	+ "			}\r\n"
  	+ "		]\r\n"
  	+ "	},\r\n"
  	+ "	\"extension\": {}\r\n"
  	+ "}";
  
  
  public static void main(String[] args) throws InterruptedException, ExecutionException, InvalidLicenceException,
	  IOException {
      new LoadOptimizationFromJsonString().example();
  }
  
  public String toString() {
      return "Loading the current optimization state from a JSON String. The JSON string is wrapped in a bzip stream to allow default processing."
      	+ " By default, BZIP is always in use.";
  }

  public void example() throws InterruptedException, ExecutionException, InvalidLicenceException, IOException {

      // Set the license via helper
      ExampleLicenseHelper.setLicense(this);

      this.invokeFromJson(JSON_SNAPSHOT, this);

      // Set the Properties
      this.setProperties();

      attachToObservables(this);

      this.startRunAsync().get();
  }

  private void setProperties() {

      Properties props = new Properties();

      props.setProperty("JOptExitCondition.JOptGenerationCount", "2000");
      props.setProperty("JOpt.Algorithm.PreOptimization.SA.NumIterations", "100000");
      props.setProperty("JOpt.Algorithm.PreOptimization.SA.NumRepetions", "1");
      props.setProperty("JOptLicense.CheckAutoLicensce", "FALSE");
      props.setProperty("JOpt.NumCPUCores", "4");

      this.addElement(props);
  }

  private void invokeFromJson(String json, IOptimization opti) throws IOException {

      IOptimizationImporter importer = new OptimizationJSONImporter();
      importer.update(compressStringToBZip2Stream(json), opti);
  }
  
  
  
  public static InputStream compressStringToBZip2Stream(String input) throws IOException {
      ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

      // Create a BZip2 output stream wrapping the ByteArrayOutputStream
      try (BZip2CompressorOutputStream bzOut = new BZip2CompressorOutputStream(byteArrayOutputStream)) {
          bzOut.write(input.getBytes());
      } // Try does automatically call finish() => Don't do it twice by adding it inside the try statement

      // Create an InputStream from the compressed byte array
      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());

      return byteArrayInputStream; // This is now a valid BZip2 stream
  }
  
  

  @Override
  public void onAsynchronousOptimizationResult(IOptimizationResult rapoptResult) {
      System.out.println(rapoptResult);
  }

  /*
   * 
   * 
   * 
   */

  /**
   * Attach to different Events (Observables) of the optimization instance.
   *
   * @param opti the optimization instance
   */
  private static void attachToObservables(IOptimization opti) {

      opti.getOptimizationEvents().progressSubject().subscribe(p -> {
	  System.out.println(p.getProgressString());
      });

      opti.getOptimizationEvents().warningSubject().subscribe(w -> {
	  System.out.println(w.toString());
      });

      opti.getOptimizationEvents().statusSubject().subscribe(s -> {
	  System.out.println(s.toString());
      });

      opti.getOptimizationEvents().errorSubject().subscribe(e -> {
	  System.out.println(e.toString());
      });
  }

}
